ALTER TABLE `bp_admins` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_admin_groups` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_bans` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_bans` MODIFY `reason` VARCHAR(100) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_chat` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_chat` MODIFY `message` VARCHAR(256) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_countries` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_countries` MODIFY `country_name` VARCHAR(100) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_flags` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_flags` MODIFY `flag` VARCHAR(1) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_flags` MODIFY `name` VARCHAR(30) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_mutegag` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_mutegag` MODIFY `reason` VARCHAR(150) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_panel_admins` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_panel_admins` MODIFY `steamid` VARCHAR(20) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_players` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_players` MODIFY `steamid` VARCHAR(20) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_players` MODIFY `country` VARCHAR(2) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_panel_admins` MODIFY `steamid` VARCHAR(20) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_players_ip` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_players_ip` MODIFY `ip` VARCHAR(20) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_players_online` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_players_username` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_players_username` MODIFY `username` VARCHAR(128) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_servers` COLLATE='utf8mb4_unicode_ci';
ALTER TABLE `bp_servers` MODIFY `name` VARCHAR(100) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_servers` MODIFY `ip` VARCHAR(20) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_servers` MODIFY `rcon_pw` VARCHAR(50) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE `bp_admin_groups` DROP COLUMN `server`;
ALTER TABLE `bp_admins` ADD COLUMN `aid` INT(11) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`aid`);
ALTER TABLE `bp_admins` DROP INDEX `pid_sid`, ADD INDEX `pid` (`pid`);
ALTER TABLE `bp_admin_groups` ADD COLUMN `isadmin` INT(1) NOT NULL DEFAULT '0' AFTER `usetime`;
